# Generated by Django 5.2.4 on 2025-07-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_remove_category_icon_and_more'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transacted_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='note',
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transacted_at',
            field=models.DateTimeField(verbose_name='Transaction Date'),
        ),
    ]
