# Generated by Django 5.2.4 on 2025-07-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited At'),
        ),
    ]
