# Generated by Django 5.2.4 on 2025-09-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_transaction_created_at_and_more'),
    ]

    operations = [
    ]
