# Generated by Django 5.2.4 on 2025-09-17 18:36

from django.db import migrations
from django.conf import settings

def create_workspaces_and_assign_expenses(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    Workspace = apps.get_model("workspaces", "Workspace")
    Expense = apps.get_model("expenses", "Transaction")

    # Step 1: Create a workspace for each user
    user_to_ws = {}
    for user in User.objects.all().order_by("id"):
        ws, _ = Workspace.objects.get_or_create(
            name=f"{user.username}'s Workspace",
            owner=user
        )
        ws.members.add(user)
        user_to_ws[user.id] = ws

    # Step 2: Assign all existing expenses to the first user's workspace
    first_user = User.objects.order_by("id").first()
    if first_user:
        first_user_ws = user_to_ws[first_user.id]
        Expense.objects.filter(workspace__isnull=True).update(workspace=first_user_ws)


def reverse_func(apps, schema_editor):
    # reverse migration: remove all workspace assignments
    Expense = apps.get_model("yourappname", "Expense")
    Workspace = apps.get_model("yourappname", "Workspace")

    Expense.objects.update(workspace=None)
    Workspace.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_transaction_created_by_transaction_workspace'),
        ('workspaces', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_workspaces_and_assign_expenses, reverse_code=reverse_func),
    ]
