# Generated by Django 5.2.4 on 2025-07-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('fa', 'فارسی')], max_length=2, unique=True, verbose_name='Language Code')),
                ('flag_image', models.ImageField(help_text='Upload a flag image (recommended size: 32x24px)', upload_to='flags/', verbose_name='Flag Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Flag Icon',
                'verbose_name_plural': 'Flag Icons',
                'ordering': ['language_code'],
            },
        ),
    ]
